create table loginDetails(
ID INTEGER PRIMARY KEY NOT NULL,
USERNAME VARCHAR(25) NOT NULL,
PASSWORD VARCHAR(15) NOT NULL
);

create table RegistrationDetails(
ID INTEGER PRIMARY KEY NOT NULL,
FIRSTNAME VARCHAR(30) NOT NULL,
LASTNAME VARCHAR(30) NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
PHONE_NUMBER LONG NOT NULL,
DATEOFBIRTH DATE NOT NULL,
ADDRESS VARCHAR(50) NOT NULL,
USERNAME VARCHAR(25) NOT NULL,
PASSWORD VARCHAR(15) NOT NULL
);